### ISSUE TITLE
Fails in ES5 environments

### ISSUE THREAD

**Issue by rtsao** [jonathanp/xml-beautifier#1]
String.prototype.repeat is an ES6 feature. This does not get polyfilled by the Babel ES2015 preset.

More info here: http://www.2ality.com/2015/12/babel6-helpersstandard-library.html#accessing-methods-normally

Because this is a module, you should not use `babel-polyfill`.

Instead, I recommend just using https://www.npmjs.com/package/repeat-string if you want ES5 support.

**Comment by svenheden** [comment]
This is a great suggestion, thanks!
