### ISSUE TITLE
Self-closing tags without />

### ISSUE THREAD

**Issue by dominictobias** [jonathanp/xml-beautifier#3]
Thanks for this, it's the only one I tried that worked and added bonus of not being 10,000 lines long.

One thing I noticed is that it incorrectly indents if a tag is self-closing but doesn't have `/>`, which seems to just be the default thing Chrome 51 or React is doing (when getting html from `innerHtml`):

![screen shot 2016-06-17 at 16 13 23](https://cloud.githubusercontent.com/assets/760314/16155340/d7ef2fc8-34a6-11e6-9213-0f102e461a0c.png)

One other minor thing is that it drops the closing tag to a new line even if there is no content which seems maybe unnecessary but meh.

![screen shot 2016-06-17 at 16 17 43](https://cloud.githubusercontent.com/assets/760314/16155384/11f339f8-34a7-11e6-9ff6-9249efdf9b97.png)

**Comment by stevendesu** [comment]
I don't know if this is a bug, necessarily. This is an _**XML**_ beautifier, not an _**HTML**_ beautifier. The `<input>` tag being self-closing is specific to HTML

**Comment by dominictobias** [comment]
Yeah fair point!

**Comment by stevendesu** [comment]
@DominicTobias if you need something that properly indents HTML, I spent about 4 hours yesterday tooling around with a script that might help.

There are several tools for beautifying HTML ([js-beautify](https://www.npmjs.com/package/js-beautify), [html-tidy](https://www.npmjs.com/package/htmltidy2), or [tidy-html5](https://www.npmjs.com/package/tidy-html5)) however every single tool out there didn't handle [blade templates](https://laravel.com/docs/5.3/blade) properly. I found open issues on just about every HTML beautifier requesting blade template support, but no efforts were being made to add it.

I used [htmlparser2](https://github.com/fb55/htmlparser2) to build an abstract syntax tree then recursively parsed the tree to regenerate the source code with my preferred formatting.

It's only a "0.1" sort of thing right now. There are a few minor bugs (`<script async>` becomes `<script async="">`) and it's not configurable without editing the source code (it always indents with tabs, it indents after the `<html>` tag, it ends the file with a new-line, etc) but it fit my purposes and was pretty fun to write. I'll upload it to my github and link it -- maybe you could help me fix some of the issues 😄 It's only about 100 lines of code right now.

**Comment by stevendesu** [comment]
@DominicTobias https://github.com/stevendesu/html-formatter
