### ISSUE TITLE
No options?

### ISSUE THREAD

**Issue by mellis481** [jonathanp/xml-beautifier#5]
I love the ease of use with this library, but it's falling short to configuration.  I would like to be able to specify tab size.  Looks like default is 4; I'd like to use 2.  I would also like all nodes like this:

```
<Company>
    test
</Company>
```

To be on a single line, like this:

`<Company>test</Company>`

Is there no way of accomplishing this with your existing library?

**Comment by svenheden** [comment]
Thanks for your comment!

Tab size can be specified by providing the second argument. For example...

```const xml = beautify('<div><span>foo</span></div>', '  ');```

To be able to have the text nodes on the same line as their opening and closing tags would be nice. I currently don't have time to implement this but you are welcome to add this in a Pull Request if you like!
